<a href="https://colab.research.google.com/github/GlobalFishingWatch/gfw-api-python-client/blob/develop/notebooks/usage-guides/datasets-api.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Datasets API

This guide provides detailed instructions on how to use the [gfw-api-python-client](https://github.com/GlobalFishingWatch/gfw-api-python-client) to access various datasets available through the Global Fishing Watch API. Currently, it focuses on retrieving SAR (Synthetic Aperture Radar) fixed infrastructure data.

**Note:** See the [Datasets](https://globalfishingwatch.org/our-apis/documentation#api-dataset), [SAR (Synthetic-Aperture Radar) Data Caveats](https://globalfishingwatch.org/our-apis/documentation#sar-fixed-infrastructure-data-caveats), and [Terms of Use](https://globalfishingwatch.org/our-apis/documentation#terms-of-use) pages in the [GFW API documentation](https://globalfishingwatch.org/our-apis/documentation#introduction) for details on GFW data, API licenses, and rate limits.

## Prerequisites

Before using the `gfw-api-python-client`, ensure it is installed (see the [Getting Started](https://globalfishingwatch.github.io/gfw-api-python-client/getting-started.html) guide) and that you have obtained an API access token from the [Global Fishing Watch API portal](https://globalfishingwatch.org/our-apis/tokens).

## Installation

The `gfw-api-python-client` can be easily installed using pip:

In [1]:
# %pip install gfw-api-python-client

## Usage

Import and use `gfw-api-python-client` in your Python codes

In [2]:
import os

import gfwapiclient as gfw

In [3]:
try:
    from google.colab import userdata

    access_token = userdata.get("GFW_API_ACCESS_TOKEN")
except Exception:
    access_token = os.environ.get("GFW_API_ACCESS_TOKEN")

access_token = access_token or "<PASTE_YOUR_GFW_API_ACCESS_TOKEN_HERE>"

In [4]:
gfw_client = gfw.Client(
    access_token=access_token,
)

## Retrieving SAR Fixed Infrastructure Data by Tile Coordinates (`get_sar_fixed_infrastructure` with z, x, y)

In [5]:
z = 1
x = 0
y = 1

In [6]:
sar_infrastructure_result = await gfw_client.datasets.get_sar_fixed_infrastructure(
    z=z, x=x, y=y
)

### Access the list of SAR fixed infrastructure items as Pydantic models

In [7]:
sar_infrastructure_data = sar_infrastructure_result.data()

In [8]:
sar_infrastructure = sar_infrastructure_data[-1]

In [9]:
(
    sar_infrastructure.structure_id,
    sar_infrastructure.label,
    sar_infrastructure.lat,
    sar_infrastructure.lon,
)

(1065796, 'oil', -71.81842050325909, -12.6523216191814)

### Access the SAR fixed infrastructure items as a DataFrame

In [10]:
sar_infrastructure_df = sar_infrastructure_result.df()

In [11]:
sar_infrastructure_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1156 entries, 0 to 1155
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   structure_id          1156 non-null   int64
 1   lat                   1156 non-null   float64
 2   lon                   1156 non-null   float64
 3   label                 1156 non-null   object
 4   structure_start_date  1156 non-null   datetime64[ns, UTC]
 5   structure_end_date    857 non-null    datetime64[ns, UTC]
 6   label_confidence      1156 non-null   object
dtypes: datetime64[ns, UTC](2), float64(2), int64(1), object(2)
memory usage: 63.3+ KB

In [12]:
sar_infrastructure_df.head()

,structure_id,lat,lon,label,structure_start_date,structure_end_date,label_confidence
0,128911,-14.374089,-170.707656,oil,2017-01-01 00:00:00+00:00,NaT,low
1,901458,-17.949867,-150.537969,unknown,2020-01-01 00:00:00+00:00,2020-01-01 00:00:00+00:00,high
2,1073932,-16.838022,-148.715736,unknown,2025-04-01 00:00:00+00:00,2025-04-01 00:00:00+00:00,high
3,1073227,-16.883566,-148.518017,unknown,2025-04-01 00:00:00+00:00,2025-04-01 00:00:00+00:00,high
4,1073521,-16.900634,-148.443097,unknown,2025-04-01 00:00:00+00:00,2025-04-01 00:00:00+00:00,high

## Retrieving SAR Fixed Infrastructure Data by Geometry (`get_sar_fixed_infrastructure` with geometry)

In [13]:
geometry = {
    "type": "Polygon",
    "coordinates": [
        [
            [-180.0, -85.0511287798066],
            [-180.0, 0.0],
            [0.0, 0.0],
            [0.0, -85.0511287798066],
            [-180.0, -85.0511287798066],
        ]
    ],
}

In [14]:
sar_infrastructure_result = await gfw_client.datasets.get_sar_fixed_infrastructure(
    geometry=geometry
)

In [15]:
sar_infrastructure_data = sar_infrastructure_result.data()

In [16]:
sar_infrastructure = sar_infrastructure_data[-1]

In [17]:
(
    sar_infrastructure.structure_id,
    sar_infrastructure.label,
    sar_infrastructure.lat,
    sar_infrastructure.lon,
)

(1065796, 'oil', -71.81842050325909, -12.6523216191814)

### Access the SAR fixed infrastructure items as a DataFrame

In [18]:
sar_infrastructure_df = sar_infrastructure_result.df()

In [19]:
sar_infrastructure_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1156 entries, 0 to 1155
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   structure_id          1156 non-null   int64
 1   lat                   1156 non-null   float64
 2   lon                   1156 non-null   float64
 3   label                 1156 non-null   object
 4   structure_start_date  1156 non-null   datetime64[ns, UTC]
 5   structure_end_date    857 non-null    datetime64[ns, UTC]
 6   label_confidence      1156 non-null   object
dtypes: datetime64[ns, UTC](2), float64(2), int64(1), object(2)
memory usage: 63.3+ KB

In [20]:
sar_infrastructure_df.head()

,structure_id,lat,lon,label,structure_start_date,structure_end_date,label_confidence
0,128911,-14.374089,-170.707656,oil,2017-01-01 00:00:00+00:00,NaT,low
1,901458,-17.949867,-150.537969,unknown,2020-01-01 00:00:00+00:00,2020-01-01 00:00:00+00:00,high
2,1073932,-16.838022,-148.715736,unknown,2025-04-01 00:00:00+00:00,2025-04-01 00:00:00+00:00,high
3,1073227,-16.883566,-148.518017,unknown,2025-04-01 00:00:00+00:00,2025-04-01 00:00:00+00:00,high
4,1073521,-16.900634,-148.443097,unknown,2025-04-01 00:00:00+00:00,2025-04-01 00:00:00+00:00,high