<a href="https://colab.research.google.com/github/GlobalFishingWatch/gfw-api-python-client/blob/develop/notebooks/usage-guides/datasets-api.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Datasets API

This guide provides detailed instructions on how to use the [gfw-api-python-client](https://github.com/GlobalFishingWatch/gfw-api-python-client) to access various datasets available through the Global Fishing Watch API. Currently, it focuses on retrieving SAR (Synthetic Aperture Radar) fixed infrastructure data.

**Note:** See the [Datasets](https://globalfishingwatch.org/our-apis/documentation#api-dataset), [SAR (Synthetic-Aperture Radar) Data Caveats](https://globalfishingwatch.org/our-apis/documentation#sar-fixed-infrastructure-data-caveats), and [Terms of Use](https://globalfishingwatch.org/our-apis/documentation#terms-of-use) pages in the [GFW API documentation](https://globalfishingwatch.org/our-apis/documentation#introduction) for details on GFW data, API licenses, and rate limits.

## Prerequisites

Before using the `gfw-api-python-client`, you need to obtain an API access token from the [Global Fishing Watch API portal](https://globalfishingwatch.org/our-apis/tokens)

## Installation

The `gfw-api-python-client` can be easily installed using pip:

In [1]:
# %pip install gfw-api-python-client

## Usage

In [2]:
import os
import gfwapiclient as gfw

In [3]:
try:
    from google.colab import userdata

    access_token = userdata.get("GFW_API_ACCESS_TOKEN")
except Exception as exc:
    access_token = os.environ.get("GFW_API_ACCESS_TOKEN")

access_token = access_token or "<PASTE_YOUR_GFW_API_ACCESS_TOKEN_HERE>"

In [4]:
gfw_client = gfw.Client(
    access_token=access_token,
)

## Retrieving SAR Fixed Infrastructure Data by Tile Coordinates (`get_sar_fixed_infrastructure` with z, x, y)

In [5]:
z = 1
x = 0
y = 1

In [6]:
sar_infrastructure_result = await gfw_client.datasets.get_sar_fixed_infrastructure(
    z=z, x=x, y=y
)

### Access the list of SAR fixed infrastructure items as Pydantic models

In [7]:
sar_infrastructure_data = sar_infrastructure_result.data()

In [8]:
sar_infrastructure = sar_infrastructure_data[-1]

In [9]:
(
    sar_infrastructure.structure_id,
    sar_infrastructure.label,
    sar_infrastructure.lat,
    sar_infrastructure.lon,
)

(646348, 'oil', -39.15082587013905, 177.96658840984458)

### Access the SAR fixed infrastructure items as a DataFrame

In [10]:
sar_infrastructure_df = sar_infrastructure_result.df()

In [11]:
sar_infrastructure_df.head()

,structure_id,lat,lon,label,structure_start_date,structure_end_date,label_confidence
0,170796,1.509645,-78.888106,unknown,2021-11-01 00:00:00+00:00,2021-12-01 00:00:00+00:00,high
1,254126,1.029763,-79.745796,oil,2017-01-01 00:00:00+00:00,NaT,high
2,360586,1.021449,-79.733240,oil,2017-01-01 00:00:00+00:00,NaT,high
3,237733,1.030971,-79.717878,oil,2017-01-01 00:00:00+00:00,NaT,high
4,450717,1.033458,-79.699540,oil,2017-01-01 00:00:00+00:00,NaT,high

## Retrieving SAR Fixed Infrastructure Data by Geometry (`get_sar_fixed_infrastructure` with geometry)

In [12]:
geometry = {
    "type": "Polygon",
    "coordinates": [
        [
            [-180.0, -85.0511287798066],
            [-180.0, 0.0],
            [0.0, 0.0],
            [0.0, -85.0511287798066],
            [-180.0, -85.0511287798066],
        ]
    ],
}

In [13]:
sar_infrastructure_result = await gfw_client.datasets.get_sar_fixed_infrastructure(
    geometry=geometry
)

In [14]:
sar_infrastructure_data = sar_infrastructure_result.data()

In [15]:
sar_infrastructure = sar_infrastructure_data[-1]

In [16]:
(
    sar_infrastructure.structure_id,
    sar_infrastructure.label,
    sar_infrastructure.lat,
    sar_infrastructure.lon,
)

(646348, 'oil', -39.15082587013905, 177.96658840984458)

### Access the SAR fixed infrastructure items as a DataFrame

In [17]:
sar_infrastructure_df = sar_infrastructure_result.df()

In [18]:
sar_infrastructure_df.head()

,structure_id,lat,lon,label,structure_start_date,structure_end_date,label_confidence
0,170796,1.509645,-78.888106,unknown,2021-11-01 00:00:00+00:00,2021-12-01 00:00:00+00:00,high
1,254126,1.029763,-79.745796,oil,2017-01-01 00:00:00+00:00,NaT,high
2,360586,1.021449,-79.733240,oil,2017-01-01 00:00:00+00:00,NaT,high
3,237733,1.030971,-79.717878,oil,2017-01-01 00:00:00+00:00,NaT,high
4,450717,1.033458,-79.699540,oil,2017-01-01 00:00:00+00:00,NaT,high